"""Add subscription fields to User

Revision ID: 3a8b5971fdc9
Revises: 1204ee420b64
Create Date: 2025-03-19 18:41:14.518164

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a8b5971fdc9'
down_revision = '1204ee420b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'expiry_date')
    # ### end Alembic commands ###